### ISSUE TITLE
FluentValidation

### ISSUE THREAD

**Issue by TechHoruser** [JacdDev/MealPlanner#1]
He visto que usas FluentValidation en una clase de validación en la capa de aplicación. No tengo claro si esta clase es una clase que puede usarse en esta capa ya que debería estar definida aquí o en la de dominio.

No sé si es el caso porque no dominó este lenguaje, pero sería posible que requiera que crees una interfaz en alguna de estas capas con la implementación en infraestructura, si fuese un módulo/paquete instalado como dep

**Comment by JacdDev** [comment]
Estoy de acuerdo en que esa solución es más adecuada si eres fiel las reglas de Clean Architecture, pero he decidido ser más pragmático. Desarrolladores con más renombre y experiencia que yo incluyen dependencias las capas más internas de sus propios proyectos, por lo que considero que puede ser una buena práctica. Puedes echarle un vistazo a [https://github.com/ardalis/CleanArchitecture/blob/main/src/Clean.Architecture.Core/Clean.Architecture.Core.csproj](https://github.com/ardalis/CleanArchitecture/blob/main/src/Clean.Architecture.Core/Clean.Architecture.Core.csproj) o [https://github.com/jasontaylordev/CleanArchitecture/blob/main/src/Application/Application.csproj](https://github.com/jasontaylordev/CleanArchitecture/blob/main/src/Application/Application.csproj)
